Lopocz
lyutko/TP_PV017 pull request #19
Opened 2022-04-18 09:28 UTC by niki228041

## Summary of issue

added changens to daylimeeting

## Summary of change

added changens to daylimeeting

## ClickUp

* [ClickUp ticket](https://app.clickup.com)

## CHECK LIST
- [ ]  Implemented new feature
- [ ]  Tested locally

2022-04-18 15:36 UTC, lyutko requested changes

2022-04-18 15:36 UTC, lyutko commented on Financial_Manager/FM.Client/User Ui Login/Login.xaml
> +                    <Label Content="Ім'я" Margin="30,00"></Label>
Тут краще або "логін" або ж "Ім'я користувача"

2022-04-18 15:36 UTC, lyutko commented on Financial_Manager/FM.Client/User Ui Login/Login.xaml
> +                    <Label FontSize="15" Content="Логін" HorizontalAlignment="Center" Margin="0,10"></Label>
Краще замінити на "Вхід" або "Авторизація"

2022-04-18 16:25 UTC, SweetDie commented
You need to change the window to a page

2022-04-20 17:52 UTC, lyutko approved these changes

2022-04-21 07:40 UTC, merged